[package]
name = "antbox"
description = "A cellular automata & artificial life toy."
version = "0.1.0"
license.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
antbox-animation.workspace = true
antbox-clife.workspace = true
antbox-geom.workspace = true
antbox-s2win.workspace = true
antbox-state.workspace = true
antbox-tick-timer.workspace = true
antbox-trig.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
derive-debug.workspace = true
derive-new.workspace = true
derive_more = { workspace = true, features = ["is_variant", "try_into", "unwrap"] }
env_logger.workspace = true
log.workspace = true
logging-options.workspace = true
movestate.workspace = true
rand.workspace = true
speedy2d.workspace = true
