[workspace]
resolver = "3"
members = [
  "anim",
  "antbox",
  "clife",
  "geom",
  "logging-options",
  "moveslot",
  "movestate",
  "s2win",
  "state",
  "tick",
  "trig",
]

[workspace.package]
edition = "2024"
license = "MIT"
homepage = "https://github.com/nejucomo/antbox"

[workspace.dependencies]
antbox = { version = "0.1.0", path = "antbox" }
antbox-animation = { version = "0.1.0", path = "anim" }
antbox-clife = { version = "0.1.0", path = "clife" }
antbox-geom = { version = "0.1.0", path = "geom" }
antbox-s2win = { version = "0.1.0", path = "s2win" }
antbox-state = { version = "0.1.0", path = "state" }
antbox-tick-timer = { version = "0.1.0", path = "tick" }
antbox-trig = { version = "0.1.0", path = "trig" }
logging-options = { version = "0.1.0", path = "logging-options" }
moveslot = { version = "0.1.0", path = "moveslot" }
movestate = { version = "0.1.0", path = "movestate" }

anyhow = "1.0.100"
clap = "4.5.53"
derive-debug = "0.1.2"
derive-new = "0.7.0"
derive_more = "2.0.1"
either = "1.15.0"
env_logger = "0.11.8"
extension-traits = "2.0.1"
itertools = "0.14.0"
log = "0.4.28"
num-integer = "0.1.46"
rand = "0.9.2"
rand_distr = "0.5.1"
speedy2d = "2.1.0"
test-case = "3.3.1"
wyrand = "0.3.2"
