[package]
name = "antbox-trig"
description = "Two-dimensional polar coordinate support for `antbox` graphics."
version = "0.1.0"
license.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
derive-new.workspace = true
derive_more.workspace = true
speedy2d.workspace = true
