[package]
name = "antbox-clife"
description = "Cellular automaton support for `antbox`."
version = "0.1.0"
license.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
antbox-geom.workspace = true
derive-new.workspace = true
derive_more = { workspace = true, features = [ "from", "into", "deref", "deref_mut" ] }
mealy-machine.workspace = true
