[package]
name = "antbox-state"
description = "The logical state of the `antbox` cellular automaton / artificial life toy."
version = "0.1.0"
license.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
antbox-clife.workspace = true
antbox-geom.workspace = true
clap = { workspace = true, features = ["derive"] }
derive-new.workspace = true
derive_more = { workspace = true, features = [ "from", "into", "try_unwrap" ] }
log.workspace = true
mealy-machine.workspace = true
rand.workspace = true
