[package]
name = "antbox-gameboard"
description = "The logical state of the `antbox` cellular automaton / artificial life toy."
version = "0.1.0"
license.workspace = true
homepage.workspace = true
edition.workspace = true

[dependencies]
antbox-clife.workspace = true
antbox-grid.workspace = true
clap = { workspace = true, features = ["derive"] }
derive-new.workspace = true
derive_more = { workspace = true, features = [ "from", "into", "try_unwrap", "is_variant", "try_into" ] }
either.workspace = true
log.workspace = true
movestate.workspace = true
rand.workspace = true
