[package]
name = "antbox-s2win"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
antbox-geom.workspace = true
antbox-render.workspace = true
antbox-s2render.workspace = true
derive-debug.workspace = true
derive-new.workspace = true
derive_more = { workspace = true, features = ["deref", "deref_mut", "unwrap", "is_variant"] }
extension-traits.workspace = true
mstate.workspace = true
moveslot.workspace = true
speedy2d.workspace = true
