[package]
name = "antbox-tick-timer"
description = "A very simple sleep-injecting non-realtime framerate timer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["is_variant"] }
derive-new.workspace = true
either.workspace = true
extension-traits.workspace = true
log.workspace = true
movestate.workspace = true
